flags: {}
extra-package-dbs: []
packages:
- '.'
# - location: 
#     git: https://github.com/sleexyz/hylogen
#     commit: 6a86ee32e5b869a877151f74064572225e1a0398
#   extra-dep: true
#   subdirs:
#   - hylogen
#   - hylide
extra-deps:
- hylide-0.1.5.0
- hylogen-0.1.5.0
resolver: lts-7.5
