flags: {}
extra-package-dbs: []
packages:
- '.'
- /home/slee2/projects/hylogen/hylogen
- /home/slee2/projects/hylogen/hylide
# - location: 
#   extra-dep: true
#   subdirs:
#   - hylogen
#   - hylide
# extra-deps:
# - hylide-*
# - hylogen*
resolver: lts-7.5
